### ISSUE TITLE
Bug: Runtime error co routine was never awaited

### ISSUE THREAD

**Issue by Paulmski** [Paulmski/Discord-Bot#31]
After pull request #30 When the `EventScheduler` function `schedule_events(self)` is called it gives the following error:

`/home/paulmolczanski/playground/Discord-Bot/src/__main__.py:83: RuntimeWarning: coroutine 'Loop.__call__' was never awaited
  self.schedule_events()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

Steps to reproduce:
1. Set up .env
2. Setup credentials.json
3. Remove restriction that `schedule_events(self)` can only be run at 6 am

**Comment by Paulmski** [comment]
I am in the process of fixing this but another error is coming up:
`Unhandled exception in internal background task 'schedule_events'.
Traceback (most recent call last):
  File "/home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/paulmolczanski/Documents/github/Discord-Bot/src/events.py", line 85, in schedule_events
    await self.bot.http.request(route, json=event)
  File "/home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In scheduled_end_time: Cannot schedule event in the past.
In scheduled_start_time: Cannot schedule event in the past.
^C2021-12-21 16:42:04 INFO     Cleaning up tasks.
2021-12-21 16:42:04 INFO     Cleaning up after 2 tasks.
2021-12-21 16:42:04 INFO     All tasks finished cancelling.
2021-12-21 16:42:04 INFO     Closing the event loop.
2021-12-21 16:42:04 ERROR    Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Loop._loop() done, defined at /home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/ext/tasks/__init__.py:88> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn scheduled_end_time: Cannot schedule event in the past.\nIn scheduled_start_time: Cannot schedule event in the past.')>
Traceback (most recent call last):
  File "/home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/paulmolczanski/Documents/github/Discord-Bot/src/events.py", line 85, in schedule_events
    await self.bot.http.request(route, json=event)
  File "/home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In scheduled_end_time: Cannot schedule event in the past.
In scheduled_start_time: Cannot schedule event in the past.`

**Comment by tuanyvan** [comment]
Looks like [Error 50035](https://discord.com/developers/docs/topics/opcodes-and-status-codes#:~:text=to%20bulk%20delete-,50035,-Invalid%20form%20body) is normal if the error message is that scheduled events can't be made in the past. Since the Google Sheets contains time for courses before 5:30 PM EST, any JSON payload that attempts to schedule an event before the current time will be rejected.

For debug purposes, we could always adjust the time for the event to a time that's after 5:30 PM EST, and then switch it back when need be. That is what I did when debugging. Since this event is designed to fire at 6AM EST, there should be no problem with Error 50035 in a normal environment.

**Comment by Paulmski** [comment]
Okay makes sense, I think it is something that should still be handled in case the time of day gets changed or other functionality is added that impacts it.

The original issue still needs to be fixed still though.

**Comment by tuanyvan** [comment]
The fix should be in my pull request. I thought if the previous class we made for announcing events had no trouble with await, it must be the way the schedule_events function is called in the new class.

I think when #6 eventually gets its interactivity programmed, we could have events rescheduled by vote or some form of moderation command.

**Comment by Paulmski** [comment]
Fixed
